set yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -26,6 +26,9 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
+      - name: Debug curl to test URL (insecure)
+        run: curl -kIv https://mantis.simasfinance.co.id || echo "⚠️ curl failed, but continuing workflow..."
+
       - name: Run Playwright tests
         run: npx playwright test || true
 
